services:
  backend:
    build: ./backend
    container_name: tonalkab_backend
    ports:
      - "8000:8000" #- "127.0.0.1:8000:8000" en el servidor
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tonalkab_net

  db:
    image: mysql:8.0
    container_name: tonalkab_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"  # solo para desarrollo
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tonalkab_net

networks:
  tonalkab_net:

volumes:
  db_data: