# docker-compose.yml (Base común)
services:
  backend:
    build: ./backend
    container_name: tonalkab_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tonalkab_net
    #ports:
    #  - "127.0.0.1:8000:8000" # Seguro por defecto

  db:
    image: mysql:8.0
    container_name: tonalkab_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tonalkab_net

networks:
  tonalkab_net:
volumes:
  db_data: